### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by chmielwork** [eddiesigner/sketch-map-generator#24]
Hey guys,

I'm having a small issue with your plugin. My steps are the same from your tips:

> Create a shape and select it. 
> Run the Map Generator Plugin:
> 
> Google Maps
> 
> Plugins > Map Generator > Generate a Map using Google Maps

And what I'm getting after these steps is blank shape—without map.

What's wrong? I've re-installed Sketch, Plugin and update everything.

**Comment by eddiesigner** [comment]
Hi!

Can you try please to follow these steps? 🤔

https://github.com/eddiesigner/sketch-map-generator/wiki/Debugging-Sketch-Map-Generator

Cheers.

**Comment by CharlieMouton** [comment]
I'm having trouble as well with the plugin. My guess is Sketch 48 is causing issues. I am running Sketch 48 with plugin version 2.0.2. Running High Sierra version 10.13.1.

I'm attaching a .txt with my error logs. Thanks in advance for your help!

[map_generator_error.txt](https://github.com/eddiesigner/sketch-map-generator/files/1535720/map_generator_error.txt)

 Best,

Charlie

**Comment by eddiesigner** [comment]
I already fixed the problem, please update to the version 2.0.3 :)

**Comment by sladanyi-dynamite** [comment]
Hi Eddie,

Seems like the problem is back with Sketch 48.1, any chance for a new fix?

S.

**Comment by sladanyi-dynamite** [comment]
Nevermind... works now :)
